name: Test
on: [push, workflow_call]
jobs:
  Run-Tests:
    if: ${{ ( github.event_name == 'push' && ! startsWith(github.ref, 'refs/tags/')) || github.event_name == 'release'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event_name}}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:headless